# render.yaml
services:
  - type: web
    name: student-cabinet-mvp
    env: python
    region: frankfurt      # или любая другая доступная
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4